FROM ubuntu:22.10

ENV DEBIAN_FRONTEND=noninteractive

# Cambiar los repositorios a old-releases
RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://old-releases.ubuntu.com/ubuntu/|g' /etc/apt/sources.list && \
    sed -i 's|http://security.ubuntu.com/ubuntu|http://old-releases.ubuntu.com/ubuntu|g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y openssh-client openssh-server && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Crear usuario y configurar contraseña
RUN useradd -ms /bin/bash prueba && \
    echo "prueba:prueba" | chpasswd && \
    mkdir -p /var/run/sshd

# Exponer el puerto SSH
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
