version: '3.9'
services:
  c1:
    build: 
      context: ./C1
    container_name: c1_container
    tty: true
  c2:
    build:
      context: ./C2
    container_name: c2_container
    tty: true
  c3:
    build:
      context: ./C3
    container_name: c3_container
    tty: true
  c4_s1:
    build:
      context: ./C4_S1
    container_name: c4_s1_container
    ports:
      - "22:22" # Para acceder al servidor SSH desde fuera
    tty: true
